# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pkvqoGtikvnRyXX1IZfkIGyrCQlxOpjd
"""

import re
import pandas as pd
import streamlit as st
from datasets import load_dataset
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Set page configuration
st.set_page_config(
    page_title="AI vs Human Text Detector", page_icon="🤖", layout="wide"
)


# Helper function for text cleaning
def clean_text(text):
    prefixes = [
        "As an AI language model",
        "I am an AI",
        "Certainly!",
        "Sure, I can help",
    ]
    for p in prefixes:
        text = text.replace(p, "")
    text = re.sub(r"\s+", " ", text).strip()
    return text


# Cache dataset loading & model training to prevent rerunning on every user input
@st.cache_resource
def train_pipeline():
    # 1. Load subset of HC3 dataset
    raw_dataset = load_dataset(
        "Hello-SimpleAI/hc3", "default", split="train[:2000]"
    )
    df = pd.DataFrame(raw_dataset)

    # 2. Extract and Label
    human_df = (
        df[["human_answers"]]
        .explode("human_answers")
        .rename(columns={"human_answers": "text"})
    )
    human_df["label"] = 0

    ai_df = (
        df[["chatgpt_answers"]]
        .explode("chatgpt_answers")
        .rename(columns={"chatgpt_answers": "text"})
    )
    ai_df["label"] = 1

    final_df = pd.concat([human_df, ai_df], ignore_index=True).dropna()
    final_df["text"] = final_df["text"].apply(clean_text)
    final_df = final_df[final_df["text"].str.split().str.len() > 10]

    # 3. Train-Test Split & TF-IDF Vectorization
    X_train, _, y_train, _ = train_test_split(
        final_df["text"],
        final_df["label"],
        test_size=0.2,
        random_state=42,
        stratify=final_df["label"],
    )

    tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
    X_train_tfidf = tfidf.fit_transform(X_train)

    # 4. Train Classifier
    model = LogisticRegression()
    model.fit(X_train_tfidf, y_train)

    return tfidf, model


# --- App UI Layout ---
st.title("🤖 Human vs AI Text Classification App")
st.write(
    "Enter a text sample below to evaluate whether it was likely written by a **Human** or generated by **AI**."
)

# Load pipeline with spinner
with st.spinner("Loading dataset and training model..."):
    tfidf, model = train_pipeline()

st.success("Model pipeline ready!")

# User input text box
user_input = st.text_area(
    "Input Text:",
    height=200,
    placeholder="Paste paragraph or response here...",
)

col1, col2 = st.columns([1, 4])

with col1:
    analyze_btn = st.button("Analyze Text", type="primary")

if analyze_btn:
    cleaned_input = clean_text(user_input)
    word_count = len(cleaned_input.split())

    if word_count < 10:
        st.warning(
            "Please enter a longer text sample (at least 10 words) for accurate evaluation."
        )
    else:
        # Transform input and predict probabilities
        input_tfidf = tfidf.transform([cleaned_input])
        prediction = model.predict(input_tfidf)[0]
        probs = model.predict_proba(input_tfidf)[0]

        ai_prob = probs[1] * 100
        human_prob = probs[0] * 100

        st.divider()
        st.subheader("Results")

        if prediction == 1:
            st.error(f"**Predicted Origin:** Likely AI-Generated")
        else:
            st.success(f"**Predicted Origin:** Likely Human-Written")

        # Display Probability Metrics
        m1, m2 = st.columns(2)
        m1.metric("Human Confidence", f"{human_prob:.1f}%")
        m2.metric("AI Confidence", f"{ai_prob:.1f}%")

        # Visual progress bars
        st.write("**Probability Breakdown:**")
        st.write("Human")
        st.progress(int(human_prob))
        st.write("AI")
        st.progress(int(ai_prob))